name: npm-publish
on:
  release:
    types: [published]
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Make sure package.json lists same version as this tag
      run: test  "$(git describe --tags | sed 's/^v//')" == "$(yarn version  --non-interactive | tail -n +2 | cut -d':' -f2 | head -1 | tr -d ' ')"
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 8.12.0
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn publish --non-interactive
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: yarn publish --non-interactive
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
